version: '3.2'
services:

  database:
    image: mariadb:latest
    env_file: ./build/envfile
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
        - "$HOST_DB_PORT:3306"
    volumes:
      #if you insert init data
      #- ../app/initial.sql:/docker-entrypoint-initdb.d/initial.sql
      - ./data:/var/lib/mysql
    networks:
        - app

  webserver:
    build: build
    image: ubuntu_server:apache_php_71_dev
    # ports:
    #   - "8080:80"
    volumes:
      - ./project:/var/www
      - ./build/php.ini:/usr/local/etc/php/conf.d/php.ini
      # - ./log/error.log:/var/log/apache2/localhost_error.log
      # - ./log/access.log:/var/log/apache2/localhost_access.log
    links:
      - database
    environment:
        - VIRTUAL_HOST=$VIRTUAL_HOST
    networks:
       - external_nginx_proxy
       - app
    #command: /usr/sbin/apache2 -D FOREGROUND
networks:
  app:
  external_nginx_proxy:
    external:
        name: proxy_net
