version: '3'
services:

  # data:
  #   image: busybox
  #   volumes:
  #     - ../mysql:/var/lib/mysql

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: development
      MYSQL_PASSWORD: development
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "13306:3306"
    volumes:
      #if you insert init data
      #- ../app/initial.sql:/docker-entrypoint-initdb.d/initial.sql
      - ./data:/var/lib/mysql

  webserver:
    build: build
    image: ubuntu_server:apache_php_71_dev
    ports:
      - "8080:80"
    volumes:
      - ./project:/var/www
      - ./log/error.log:/var/log/apache2/localhost_error.log
      - ./log/access.log:/var/log/apache2/localhost_access.log
      - ./build/php.ini:/usr/local/etc/php/conf.d/php.ini
    links:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: project
      DATABASE_USER: development
      DATABASE_PASSWORD: development
    #command: /usr/sbin/apache2 -D FOREGROUND
