version: '3'
services:

  # data:
  #   image: busybox
  #   volumes:
  #     - ../mysql:/var/lib/mysql

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: development
      MYSQL_PASSWORD: development
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "13306:3306"
    volumes:
      #if you insert init data
      #- ../app/initial.sql:/docker-entrypoint-initdb.d/initial.sql
      - ../data:/var/lib/mysql
    container_name: php_database

  web:
    build: ./php71-apache
#     build: ./php56-apache
    ports:
      - "8080:80"
    volumes:
      - ../project:/var/www
      - ./php71-apache/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ../log/error.log:/var/log/apache2/localhost_error.log
      - ../log/access.log:/var/log/apache2/localhost_access.log
    links:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: project
      DATABASE_USER: development
      DATABASE_PASSWORD: development
    container_name: php_web
    #command: /usr/sbin/apache2 -D FOREGROUND
